In [8]:
import pandas as pd
df = pd.read_csv("powerbi.csv")
print(df)

           Model     Name                         Email Director  \
0         Basic     James    James Tony@Sample_Demo.com   Morris
1         Basic      John     John Tony@Sample_Demo.com   Morris
2         Basic    Robert   Robert Tony@Sample_Demo.com   Morris
3         Basic   Michael  Michael Tony@Sample_Demo.com   Morris
4         Basic   William  William Tony@Sample_Demo.com   Morris
5         Basic     David    David Tony@Sample_Demo.com   Morris
6         Basic   Richard  Richard Tony@Sample_Demo.com   Morris
7         Basic   Charles  Charles Tony@Sample_Demo.com   Morris
8         Basic    Joseph   Joseph Tony@Sample_Demo.com   Morris
9         Basic    Thomas   Thomas Tony@Sample_Demo.com   Morris
10        Basic    Edward   Edward Tony@Sample_Demo.com   Morris
11        Basic    Daniel   Daniel Tony@Sample_Demo.com   Morris
12        Basic      Paul     Paul Tony@Sample_Demo.com   Morris
13        Basic      Mark     Mark Tony@Sample_Demo.com   Morris
14        Basic    Donald   Donald Tony@Sample_Demo.com   Morris
15        Basic      Jeff     Jeff Tony@Sample_Demo.com   Morris
16        Basic   Kenneth  Kenneth Tony@Sample_Demo.com   Morris
17        Basic    Steven   Steven Tony@Sample_Demo.com   Morris
18        Basic     Kevin    Kevin Tony@Sample_Demo.com   Morris
19  Intermediate    James    James Tony@Sample_Demo.com   Morris
20  Intermediate     John     John Tony@Sample_Demo.com   Morris
21  Intermediate   Robert   Robert Tony@Sample_Demo.com   Morris
22  Intermediate  Michael  Michael Tony@Sample_Demo.com   Morris
23  Intermediate  William  William Tony@Sample_Demo.com   Morris
24  Intermediate    David    David Tony@Sample_Demo.com   Morris
25  Intermediate  Richard  Richard Tony@Sample_Demo.com   Morris
26  Intermediate  Charles  Charles Tony@Sample_Demo.com   Morris
27  Intermediate   Joseph   Joseph Tony@Sample_Demo.com   Morris
28  Intermediate   Thomas   Thomas Tony@Sample_Demo.com   Morris
29  Intermediate   Edward   Edward Tony@Sample_Demo.com   Morris
30  Intermediate   Daniel   Daniel Tony@Sample_Demo.com   Morris
31  Intermediate     Paul     Paul Tony@Sample_Demo.com   Morris
32  Intermediate     Mark     Mark Tony@Sample_Demo.com   Morris
33  Intermediate   Donald   Donald Tony@Sample_Demo.com   Morris
34  Intermediate     Jeff     Jeff Tony@Sample_Demo.com   Morris
35  Intermediate  Kenneth  Kenneth Tony@Sample_Demo.com   Morris
36  Intermediate   Steven   Steven Tony@Sample_Demo.com   Morris
37  Intermediate    Kevin    Kevin Tony@Sample_Demo.com   Morris

   Senior Manager Please select your Manager Name:  \
0             Dan                              Dan
1           Lewis                            Lewis
2             Sam                              Sam
3            Kent                             Kent
4            Wade                             Wade
5             Dan                              Dan
6           Lewis                            Lewis
7             Sam                              Sam
8            Kent                             Kent
9            Wade                             Wade
10            Dan                              Dan
11          Lewis                            Lewis
12            Sam                              Sam
13           Kent                             Kent
14           Wade                             Wade
15            Dan                              Dan
16          Lewis                            Lewis
17            Sam                              Sam
18           Kent                             Kent
19           Wade                             Wade
20            Dan                              Dan
21          Lewis                            Lewis
22            Sam                              Sam
23           Kent                             Kent
24           Wade                             Wade
25            Dan                              Dan
26          Lewis                            Lewis
27            Sam                              Sam
28           Kent                             Kent
29           Wade                             Wade
30            Dan                              Dan
31          Lewis                            Lewis
32            Sam                              Sam
33           Kent                             Kent
34           Wade                             Wade
35            Dan                              Dan
36          Lewis                            Lewis
37            Sam                              Sam

    Please enter your Employee ID: Please enter your Dell Email ID:  Gender  \
0                          8645382            James Tony@Sample.com    Male
1                          8645383             John Tony@Sample.com    Male
2                          8645384           Robert Tony@Sample.com    Male
3                          8645385          Michael Tony@Sample.com  Female
4                          8645386          William Tony@Sample.com  Female
5                          8645387            David Tony@Sample.com  Female
6                          8645388          Richard Tony@Sample.com  Female
7                          8645389          Charles Tony@Sample.com  Female
8                          8645390           Joseph Tony@Sample.com  Female
9                          8645391           Thomas Tony@Sample.com    Male
10                         8645392           Edward Tony@Sample.com  Female
11                         8645393           Daniel Tony@Sample.com    Male
12                         8645394             Paul Tony@Sample.com  Female
13                         8645395             Mark Tony@Sample.com  Female
14                         8645396           Donald Tony@Sample.com    Male
15                         8645397             Jeff Tony@Sample.com    Male
16                         8645398          Kenneth Tony@Sample.com    Male
17                         8645399           Steven Tony@Sample.com  Female
18                         8645400            Kevin Tony@Sample.com  Female
19                         8645401            James Tony@Sample.com    Male
20                         8645402             John Tony@Sample.com    Male
21                         8645403           Robert Tony@Sample.com  Female
22                         8645404          Michael Tony@Sample.com  Female
23                         8645405          William Tony@Sample.com  Female
24                         8645406            David Tony@Sample.com  Female
25                         8645407          Richard Tony@Sample.com  Female
26                         8645408          Charles Tony@Sample.com    Male
27                         8645409           Joseph Tony@Sample.com  Female
28                         8645410           Thomas Tony@Sample.com  Female
29                         8645411           Edward Tony@Sample.com    Male
30                         8645412           Daniel Tony@Sample.com    Male
31                         8645413             Paul Tony@Sample.com    Male
32                         8645414             Mark Tony@Sample.com    Male
33                         8645415           Donald Tony@Sample.com    Male
34                         8645416             Jeff Tony@Sample.com  Female
35                         8645417          Kenneth Tony@Sample.com  Female
36                         8645418           Steven Tony@Sample.com  Female
37                         8645419            Kevin Tony@Sample.com  Female

           Job Level Attendance    Team  Attendance Status  Salary      Date  \
0          Executive    Present  Team 4                  1   10000  2/1/2022
1   Senior Executive     Absent  Team 5                  0   11000  2/1/2022
2            Anyalst    Present  Team 4                  1   12000  2/1/2022
3     Senior Analyst    Present  Team 2                  1   13000  2/1/2022
4          Team Lead    Present  Team 2                  1   14000  2/1/2022
5          Executive     Absent  Team 5                  0   15000  2/1/2022
6   Senior Executive    Present  Team 2                  1   16000  2/1/2022
7            Anyalst    Present  Team 2                  1   17000  2/1/2022
8     Senior Analyst    Present  Team 1                  1   18000  2/1/2022
9          Team Lead     Absent  Team 4                  0   19000  2/1/2022
10         Executive     Absent  Team 2                  0   20000  2/1/2022
11  Senior Executive    Present  Team 4                  1   21000  2/1/2022
12           Anyalst    Present  Team 3                  1   22000  2/1/2022
13    Senior Analyst    Present  Team 5                  1   23000  2/1/2022
14         Team Lead    Present  Team 5                  1   24000  2/1/2022
15         Executive     Absent  Team 5                  0   25000  2/1/2022
16  Senior Executive    Present  Team 5                  1   26000  2/1/2022
17           Anyalst    Present  Team 5                  1   27000  2/1/2022
18    Senior Analyst    Present  Team 1                  1   28000  2/1/2022
19         Team Lead    Present  Team 4                  1   10000  2/1/2022
20         Executive    Present  Team 4                  1   10000  2/1/2022
21  Senior Executive    Present  Team 2                  1   10000  2/1/2022
22           Anyalst    Present  Team 2                  1   10000  2/1/2022
23    Senior Analyst    Present  Team 2                  1   10000  2/1/2022
24         Team Lead    Present  Team 2                  1   10000  2/1/2022
25         Executive    Present  Team 1                  1   10000  2/1/2022
26  Senior Executive    Present  Team 4                  1   10000  2/1/2022
27           Anyalst    Present  Team 3                  1   10000  2/1/2022
28    Senior Analyst    Present  Team 5                  1   10000  2/1/2022
29         Team Lead    Present  Team 5                  1   10000  2/1/2022
30         Executive    Present  Team 5                  1   10000  2/1/2022
31  Senior Executive    Present  Team 2                  1   15000  2/1/2022
32           Anyalst    Present  Team 2                  1   20000  2/1/2022
33    Senior Analyst    Present  Team 2                  1   25000  2/1/2022
34         Team Lead    Present  Team 1                  1   30000  2/1/2022
35         Executive    Present  Team 4                  1   35000  2/1/2022
36  Senior Executive    Present  Team 3                  1   40000  2/1/2022
37           Anyalst    Present  Team 5                  1   45000  2/1/2022

   Month Quarter  Bonus
0    Feb      Q1    500
1    Feb      Q1    550
2    Feb      Q1    600
3    Feb      Q1    650
4    Feb      Q1    700
5    Feb      Q1    750
6    Feb      Q1    800
7    Feb      Q1    850
8    Feb      Q1    900
9    Feb      Q1    950
10   Feb      Q1   1000
11   Feb      Q1   1050
12   Feb      Q1   1100
13   Feb      Q1   1150
14   Feb      Q1   1200
15   Feb      Q1   1250
16   Feb      Q1   1300
17   Feb      Q1   1350
18   Feb      Q1   1400
19   Feb      Q1    500
20   Feb      Q1    500
21   Feb      Q1    500
22   Feb      Q1    500
23   Feb      Q1    500
24   Feb      Q1    500
25   Feb      Q1    500
26   Feb      Q1    500
27   Feb      Q1    500
28   Feb      Q1    500
29   Feb      Q1    500
30   Feb      Q1    500
31   Feb      Q1    750
32   Feb      Q1   1000
33   Feb      Q1   1250
34   Feb      Q1   1500
35   Feb      Q1   1750
36   Feb      Q1   2000
37   Feb      Q1   2250

In [10]:
import pandas as pd
df = pd.read_csv("powerbi.csv")
print(df.to_string())

           Model     Name                         Email Director Senior Manager Please select your Manager Name:  Please enter your Employee ID: Please enter your Dell Email ID:  Gender         Job Level Attendance    Team  Attendance Status  Salary      Date Month Quarter  Bonus
0         Basic     James    James Tony@Sample_Demo.com   Morris            Dan                              Dan                         8645382            James Tony@Sample.com    Male         Executive    Present  Team 4                  1   10000  2/1/2022   Feb      Q1    500
1         Basic      John     John Tony@Sample_Demo.com   Morris          Lewis                            Lewis                         8645383             John Tony@Sample.com    Male  Senior Executive     Absent  Team 5                  0   11000  2/1/2022   Feb      Q1    550
2         Basic    Robert   Robert Tony@Sample_Demo.com   Morris            Sam                              Sam                         8645384           Robert Tony@Sample.com    Male           Anyalst    Present  Team 4                  1   12000  2/1/2022   Feb      Q1    600
3         Basic   Michael  Michael Tony@Sample_Demo.com   Morris           Kent                             Kent                         8645385          Michael Tony@Sample.com  Female    Senior Analyst    Present  Team 2                  1   13000  2/1/2022   Feb      Q1    650
4         Basic   William  William Tony@Sample_Demo.com   Morris           Wade                             Wade                         8645386          William Tony@Sample.com  Female         Team Lead    Present  Team 2                  1   14000  2/1/2022   Feb      Q1    700
5         Basic     David    David Tony@Sample_Demo.com   Morris            Dan                              Dan                         8645387            David Tony@Sample.com  Female         Executive     Absent  Team 5                  0   15000  2/1/2022   Feb      Q1    750
6         Basic   Richard  Richard Tony@Sample_Demo.com   Morris          Lewis                            Lewis                         8645388          Richard Tony@Sample.com  Female  Senior Executive    Present  Team 2                  1   16000  2/1/2022   Feb      Q1    800
7         Basic   Charles  Charles Tony@Sample_Demo.com   Morris            Sam                              Sam                         8645389          Charles Tony@Sample.com  Female           Anyalst    Present  Team 2                  1   17000  2/1/2022   Feb      Q1    850
8         Basic    Joseph   Joseph Tony@Sample_Demo.com   Morris           Kent                             Kent                         8645390           Joseph Tony@Sample.com  Female    Senior Analyst    Present  Team 1                  1   18000  2/1/2022   Feb      Q1    900
9         Basic    Thomas   Thomas Tony@Sample_Demo.com   Morris           Wade                             Wade                         8645391           Thomas Tony@Sample.com    Male         Team Lead     Absent  Team 4                  0   19000  2/1/2022   Feb      Q1    950
10        Basic    Edward   Edward Tony@Sample_Demo.com   Morris            Dan                              Dan                         8645392           Edward Tony@Sample.com  Female         Executive     Absent  Team 2                  0   20000  2/1/2022   Feb      Q1   1000
11        Basic    Daniel   Daniel Tony@Sample_Demo.com   Morris          Lewis                            Lewis                         8645393           Daniel Tony@Sample.com    Male  Senior Executive    Present  Team 4                  1   21000  2/1/2022   Feb      Q1   1050
12        Basic      Paul     Paul Tony@Sample_Demo.com   Morris            Sam                              Sam                         8645394             Paul Tony@Sample.com  Female           Anyalst    Present  Team 3                  1   22000  2/1/2022   Feb      Q1   1100
13        Basic      Mark     Mark Tony@Sample_Demo.com   Morris           Kent                             Kent                         8645395             Mark Tony@Sample.com  Female    Senior Analyst    Present  Team 5                  1   23000  2/1/2022   Feb      Q1   1150
14        Basic    Donald   Donald Tony@Sample_Demo.com   Morris           Wade                             Wade                         8645396           Donald Tony@Sample.com    Male         Team Lead    Present  Team 5                  1   24000  2/1/2022   Feb      Q1   1200
15        Basic      Jeff     Jeff Tony@Sample_Demo.com   Morris            Dan                              Dan                         8645397             Jeff Tony@Sample.com    Male         Executive     Absent  Team 5                  0   25000  2/1/2022   Feb      Q1   1250
16        Basic   Kenneth  Kenneth Tony@Sample_Demo.com   Morris          Lewis                            Lewis                         8645398          Kenneth Tony@Sample.com    Male  Senior Executive    Present  Team 5                  1   26000  2/1/2022   Feb      Q1   1300
17        Basic    Steven   Steven Tony@Sample_Demo.com   Morris            Sam                              Sam                         8645399           Steven Tony@Sample.com  Female           Anyalst    Present  Team 5                  1   27000  2/1/2022   Feb      Q1   1350
18        Basic     Kevin    Kevin Tony@Sample_Demo.com   Morris           Kent                             Kent                         8645400            Kevin Tony@Sample.com  Female    Senior Analyst    Present  Team 1                  1   28000  2/1/2022   Feb      Q1   1400
19  Intermediate    James    James Tony@Sample_Demo.com   Morris           Wade                             Wade                         8645401            James Tony@Sample.com    Male         Team Lead    Present  Team 4                  1   10000  2/1/2022   Feb      Q1    500
20  Intermediate     John     John Tony@Sample_Demo.com   Morris            Dan                              Dan                         8645402             John Tony@Sample.com    Male         Executive    Present  Team 4                  1   10000  2/1/2022   Feb      Q1    500
21  Intermediate   Robert   Robert Tony@Sample_Demo.com   Morris          Lewis                            Lewis                         8645403           Robert Tony@Sample.com  Female  Senior Executive    Present  Team 2                  1   10000  2/1/2022   Feb      Q1    500
22  Intermediate  Michael  Michael Tony@Sample_Demo.com   Morris            Sam                              Sam                         8645404          Michael Tony@Sample.com  Female           Anyalst    Present  Team 2                  1   10000  2/1/2022   Feb      Q1    500
23  Intermediate  William  William Tony@Sample_Demo.com   Morris           Kent                             Kent                         8645405          William Tony@Sample.com  Female    Senior Analyst    Present  Team 2                  1   10000  2/1/2022   Feb      Q1    500
24  Intermediate    David    David Tony@Sample_Demo.com   Morris           Wade                             Wade                         8645406            David Tony@Sample.com  Female         Team Lead    Present  Team 2                  1   10000  2/1/2022   Feb      Q1    500
25  Intermediate  Richard  Richard Tony@Sample_Demo.com   Morris            Dan                              Dan                         8645407          Richard Tony@Sample.com  Female         Executive    Present  Team 1                  1   10000  2/1/2022   Feb      Q1    500
26  Intermediate  Charles  Charles Tony@Sample_Demo.com   Morris          Lewis                            Lewis                         8645408          Charles Tony@Sample.com    Male  Senior Executive    Present  Team 4                  1   10000  2/1/2022   Feb      Q1    500
27  Intermediate   Joseph   Joseph Tony@Sample_Demo.com   Morris            Sam                              Sam                         8645409           Joseph Tony@Sample.com  Female           Anyalst    Present  Team 3                  1   10000  2/1/2022   Feb      Q1    500
28  Intermediate   Thomas   Thomas Tony@Sample_Demo.com   Morris           Kent                             Kent                         8645410           Thomas Tony@Sample.com  Female    Senior Analyst    Present  Team 5                  1   10000  2/1/2022   Feb      Q1    500
29  Intermediate   Edward   Edward Tony@Sample_Demo.com   Morris           Wade                             Wade                         8645411           Edward Tony@Sample.com    Male         Team Lead    Present  Team 5                  1   10000  2/1/2022   Feb      Q1    500
30  Intermediate   Daniel   Daniel Tony@Sample_Demo.com   Morris            Dan                              Dan                         8645412           Daniel Tony@Sample.com    Male         Executive    Present  Team 5                  1   10000  2/1/2022   Feb      Q1    500
31  Intermediate     Paul     Paul Tony@Sample_Demo.com   Morris          Lewis                            Lewis                         8645413             Paul Tony@Sample.com    Male  Senior Executive    Present  Team 2                  1   15000  2/1/2022   Feb      Q1    750
32  Intermediate     Mark     Mark Tony@Sample_Demo.com   Morris            Sam                              Sam                         8645414             Mark Tony@Sample.com    Male           Anyalst    Present  Team 2                  1   20000  2/1/2022   Feb      Q1   1000
33  Intermediate   Donald   Donald Tony@Sample_Demo.com   Morris           Kent                             Kent                         8645415           Donald Tony@Sample.com    Male    Senior Analyst    Present  Team 2                  1   25000  2/1/2022   Feb      Q1   1250
34  Intermediate     Jeff     Jeff Tony@Sample_Demo.com   Morris           Wade                             Wade                         8645416             Jeff Tony@Sample.com  Female         Team Lead    Present  Team 1                  1   30000  2/1/2022   Feb      Q1   1500
35  Intermediate  Kenneth  Kenneth Tony@Sample_Demo.com   Morris            Dan                              Dan                         8645417          Kenneth Tony@Sample.com  Female         Executive    Present  Team 4                  1   35000  2/1/2022   Feb      Q1   1750
36  Intermediate   Steven   Steven Tony@Sample_Demo.com   Morris          Lewis                            Lewis                         8645418           Steven Tony@Sample.com  Female  Senior Executive    Present  Team 3                  1   40000  2/1/2022   Feb      Q1   2000
37  Intermediate    Kevin    Kevin Tony@Sample_Demo.com   Morris            Sam                              Sam                         8645419            Kevin Tony@Sample.com  Female           Anyalst    Present  Team 5                  1   45000  2/1/2022   Feb      Q1   2250

In [11]:
print(pd.options.display.max_rows)

60

In [12]:
print(pd.options.display.min_rows)

10